services:
  app:
    build: .
    command: npm run all-dev
    container_name: eventflow_app
    environment:
      - REDIS_HOST=redis
      - CHOKIDAR_USEPOLLING=true
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - redis

  db:
    image: mysql
    container_name: eventflow_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    container_name: eventflow_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: