name: Node.js CD

# Controls when the action will run.
on:
  push:
    branches: 
      - EV-11-Gerenciador-criar-ambiente-de-dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_URL: ${{ secrets.API_URL }}
      SECRET: ${{ secrets.SECRET }}
      ACCESS_TOKEN_MERCADOPAGO: ${{ secrets.ACCESS_TOKEN_MERCADOPAGO }}
      GERENCIADOR_URL: ${{ secrets.GERENCIADOR_URL }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - run: npm i

    - name: Set up environment variables
      run: |
        cat <<EOT > .env
        DATABASE_URL=${{ env.DATABASE_URL }}
        API_URL=${{ env.API_URL }}
        SECRET=${{ env.SECRET }}
        ACCESS_TOKEN_MERCADOPAGO=${{ env.ACCESS_TOKEN_MERCADOPAGO }}
        GERENCIADOR_URL=${{ env.GERENCIADOR_URL }}
        EOT

    - run: npx prisma migrate deploy

    - run: npm run build --if-present

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete -vv"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/EventFlow_Backend"
          SCRIPT_AFTER: |
            echo "dentro do vps"
            pm2 restart api  