name: Node.js CD

# Controls when the action will run.
on:
  push:
    branches: [ EV-11-Gerenciador-criar-ambiente-de-dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "mysql://u537153331_admin:eventflowAdmin2024@srv1603.hstgr.io:3306/u537153331_eventflow"
      API_URL: "https://api.eventflow.com.br"
      SECRET: "jpsjdfiaen0a9weet-q0v9je49t9qwegnwaewtq2nvasjjvnccsaxxxe"
      ACCESS_TOKEN_MERCADOPAGO: "APP_USR-3623357814451153-042315-469046950538e5b9b474f8efb927611d-1781626255"
      GERENCIADOR_URL: "https://gerenciador.eventflow.com.br"

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - run: npm i

    - run: npx prisma migrate deploy

    - run: npm run build --if-present

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          nvm use 20
          cd /EventFlow_Backend
          
          # Criar arquivo .env no servidor
          cat <<EOT > .env
          DATABASE_URL=${{ env.DATABASE_URL }}
          API_URL=${{ env.API_URL }}
          SECRET=${{ env.SECRET }}
          ACCESS_TOKEN_MERCADOPAGO=${{ env.ACCESS_TOKEN_MERCADOPAGO }}
          GERENCIADOR_URL=${{ env.GERENCIADOR_URL }}
          EOT
          
          git pull origin master
          git status
          npm install 
          npx prisma migrate deploy
          npm run build
          pm2 restart api
