name: Deploy to VPS

on:
  push:
    branches:
      - EV-11-Gerenciador-criar-ambiente-de-dev  # Altere para o branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
        cd EventFlow_Backend
        git pull origin master
        # Comandos para instalar dependências e rodar seu app
        # Por exemplo, para um app Node.js:
        npm install
        npx prisma migrate deploy
        npm run build
        pm2 restart api  # ou qualquer comando para reiniciar seu app
        EOF